const pokemonList = [
  "Greninja",
  "Arceus",
  "Mew",
  "Pikachu",
  "Sylveon",
  "Charizard",
  "Genesect",
  "Rayquaza",
  "Vaporeon", // Replaced Meloetta
  "Rhydon", // Replaced Zygarde
  "Mewtwo",
  "Eevee",
  "Jirachi",
  "Darkrai",
  "Lucario",
  "Diancie",
  "Hoopa",
  "Togepi", // Replaced Keldeo
  "Victini",
  "Manaphy",
  "Reshiram",
  "Kyogre",
  "Kyurem",
  "Magnemite",
  "Nidoking", // Replaced Shaymin
  "Yveltal",
  "Rapidash", // Replaced Giratina
  "Lugia",
  "Groudon",
  "Dialga",
  "Dedenne",
  "Archeops",
  "Zekrom",
  "Suicune",
  "Gengar",
  "Ho-Oh",
  "Xerneas",
  "Gardevoir",
  "Celebi",
  "Piplup",
  "Palkia",
  "Garchomp",
  "Regigigas",
  "Azelf",
  "Blaziken",
  "Ninetales", // Replaced Landorus
  "Glaceon",
  "Latias",
  "Jigglypuff",
  "Alakazam", // Replaced Deoxys
  "Oshawott", // Corrected spelling for Oshawatt
  "Snorlax",
  "Articuno",
  "Absol",
  "Latios",
  "Zoroark",
  "Ditto",
  "Fennekin",
  "Dragonite",
  "Hydreigon",
  "Sceptile",
  "Zapdos",
  "Leafeon",
  "Salamence",
  "Flygon",
  "Espeon",
  "Moltres",
  "Goomy",
  "Pichu",
  "Infernape",
  "Raichu",
  "Metagross",
  "Froakie",
  "Cresselia",
  "Blastoise",
  "Umbreon",
  "Emolga",
  "Arbok",
  "Milotic",
  "Lapras",
  "Swampert",
  "Meowth",
  "Beautifly",
  "Mawile",
  "Noivern",
  "Luxray",
  "Ampharos",
  "Archen",
  "Bulbasaur",
  "Armaldo",
  "Magikarp",
  "Chandelure",
  "Torchic",
  "Aerodactyl", // Replaced Thundurus
  "Flareon",
  "Porygon",
  "Chespin",
  "Raikou",
  "Machamp",
  "Mudkip",
];

export default pokemonList;
